language: python
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
      - ccache
cache:
  - ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
script:
  - ./configure
  - make
